from typing import Optional, List, Tuple

from TRAMbio.util.constants.interaction import InteractionType
from tests.util.protein_graph_utils import *

def graph_adenine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "DA".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         1.506, -8.601, 1.963, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         1.137, -9.938, 2.556, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         2.821, -8.546, 1.294, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         0.161, -8.095, 1.269, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -1.094, -8.020, 1.943, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -1.883, -6.868, 1.344, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -1.173, -5.665, 1.435, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -2.342, -7.009, -0.097, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -3.766, -7.028, -0.200, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -1.653, -5.843, -0.816, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -1.394, -4.843, 0.244, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "N9", f"A{res:04d}-{resi}:N9", "N", "",
         -0.241, -3.930, 0.143, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "C8", f"A{res:04d}-{resi}:C8", "C", "",
         1.106, -4.199, 0.191, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "N7", f"A{res:04d}-{resi}:N7", "N", "",
         1.868, -3.132, 0.144, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         0.961, -2.079, 0.091, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         1.149, -0.669, 0.029, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "N6", f"A{res:04d}-{resi}:N6", "N", "",
         2.322, -0.048, 0.000, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         0.000, 0.082, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.224, -0.521, 0.020, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         -1.468, -1.825, 0.066, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         -0.332, -2.550, 0.100, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -0.961, -7.880, 2.893, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -1.583, -8.852, 1.843, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -2.686, -6.877, 1.887, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -2.097, -7.852, -0.506, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -0.828, -6.129, -1.238, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H2''", f"A{res:04d}-{resi}:H2''", "H", "",
         -2.218, -5.477, -1.514, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -2.146, -4.232, 0.215, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H8", f"A{res:04d}-{resi}:H8", "H", "",
         1.447, -5.062, 0.252, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H61", f"A{res:04d}-{resi}:H61", "H", "",
         2.353, 0.811, -0.038, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H62", f"A{res:04d}-{resi}:H62", "H", "",
         3.050, -0.505, 0.019, start_idx + 30],
        ["ATOM", start_idx + 31, "A", res, "", resi, "H2", f"A{res:04d}-{resi}:H2", "H", "",
         -1.966, 0.041, 0.000, start_idx + 31],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H2''", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H8", f"A{res:04d}-{resi}:C8", 0.930),
        (f"A{res:04d}-{resi}:H61", f"A{res:04d}-{resi}:N6", 0.860),
        (f"A{res:04d}-{resi}:H62", f"A{res:04d}-{resi}:N6", 0.860),
        (f"A{res:04d}-{resi}:H2", f"A{res:04d}-{resi}:C2", 0.930),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.508, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.477, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.595, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.427, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.519, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.400, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.519, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.427, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.534, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.479, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.464, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.365, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.328, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.348, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.327, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.424, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.376, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.385, "base": True}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.312, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.374, "base": True}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.474, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:H8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:H61",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:H62",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:H2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.373, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.391, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N6", {"weight": 0}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N7", {"weight": 0}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C8", {"weight": 0}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N9", {"weight": 0}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N9": 1,
        f"A{res:04d}-{resi}:C8": 1,
        f"A{res:04d}-{resi}:N7": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
        f"A{res:04d}-{resi}:N6": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7", 5),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", 6),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_cytosine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "DC".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         -0.581, -6.353, 2.615, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         -0.942, -7.070, 3.871, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         0.242, -7.193, 1.682, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         -1.891, -5.706, 2.000, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -2.913, -5.108, 2.854, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -3.504, -4.042, 1.925, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -2.517, -3.055, 1.736, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -3.884, -4.570, 0.544, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -5.237, -4.232, 0.165, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -2.822, -3.967, -0.389, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -2.507, -2.686, 0.272, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         -1.193, -2.063, 0.138, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.203, -0.672, 0.056, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "O2", f"A{res:04d}-{resi}:O2", "O", "",
         -2.239, -0.020, 0.000, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         0.000, -0.040, 0.000, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         1.177, -0.709, 0.059, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "N4", f"A{res:04d}-{resi}:N4", "N", "",
         2.289, 0.020, 0.000, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.173, -2.128, 0.162, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         -0.018, -2.744, 0.215, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -2.535, -4.722, 3.659, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -3.578, -5.756, 3.136, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -4.315, -3.711, 2.344, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -3.887, -5.540, 0.509, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -2.041, -4.537, -0.463, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H2''", f"A{res:04d}-{resi}:H2''", "H", "",
         -3.164, -3.835, -1.287, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -3.130, -2.057, -0.124, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H41", f"A{res:04d}-{resi}:H41", "H", "",
         3.057, -0.364, 0.034, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H42", f"A{res:04d}-{resi}:H42", "H", "",
         2.238, 0.876, -0.072, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H5", f"A{res:04d}-{resi}:H5", "H", "",
         1.967, -2.610, 0.191, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H6", f"A{res:04d}-{resi}:H6", "H", "",
         -0.040, -3.669, 0.308, start_idx + 29],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H2''", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H6", f"A{res:04d}-{resi}:C6", 0.930),
        (f"A{res:04d}-{resi}:H5", f"A{res:04d}-{resi}:C5", 0.930),
        (f"A{res:04d}-{resi}:H41", f"A{res:04d}-{resi}:N4", 0.860),
        (f"A{res:04d}-{resi}:H42", f"A{res:04d}-{resi}:N4", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.490, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.501, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.586, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.460, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.533, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.409, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.526, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.446, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.536, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.475, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.511, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.461, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.361, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.342, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.394, "base": True}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.225, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.360, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.355, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.332, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:H6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:H5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:H41",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:H42",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.422, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:O2", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N4", {"weight": 0}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:C4", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:O2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
        f"A{res:04d}-{resi}:N4": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", 5),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_guanine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "DG".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         1.742, -9.405, 1.320, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         1.191, -10.696, 1.911, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         3.122, -9.499, 0.878, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         0.658, -8.562, 0.437, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -0.513, -8.241, 1.278, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -1.319, -7.201, 0.556, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -1.004, -5.862, 0.830, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -1.258, -7.367, -0.982, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -2.617, -7.447, -1.476, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -0.442, -6.179, -1.445, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -0.821, -5.121, -0.415, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "N9", f"A{res:04d}-{resi}:N9", "N", "",
         0.196, -4.066, -0.334, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "C8", f"A{res:04d}-{resi}:C8", "C", "",
         1.558, -4.188, -0.351, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "N7", f"A{res:04d}-{resi}:N7", "N", "",
         2.211, -3.049, -0.271, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.187, -2.109, -0.171, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         1.234, -0.691, -0.051, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "O6", f"A{res:04d}-{resi}:O6", "O", "",
         2.233, 0.041, 0.000, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         0.000, -0.084, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.158, -0.798, -0.057, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "N2", f"A{res:04d}-{resi}:N2", "N", "",
         -2.261, -0.042, 0.000, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         -1.253, -2.122, -0.164, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         -0.049, -2.717, -0.213, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -0.230, -7.910, 2.145, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -1.046, -9.034, 1.438, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -2.207, -7.372, 0.907, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -0.834, -8.173, -1.316, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         0.510, -6.366, -1.441, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H2''", f"A{res:04d}-{resi}:H2''", "H", "",
         -0.673, -5.907, -2.348, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -1.631, -4.642, -0.645, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H8", f"A{res:04d}-{resi}:H8", "H", "",
         1.988, -5.010, -0.414, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H1", f"A{res:04d}-{resi}:H1", "H", "",
         -0.041, 0.773, 0.070, start_idx + 30],
        ["ATOM", start_idx + 31, "A", res, "", resi, "H21", f"A{res:04d}-{resi}:H21", "H", "",
         -3.038, -0.411, -0.029, start_idx + 31],
        ["ATOM", start_idx + 32, "A", res, "", resi, "H22", f"A{res:04d}-{resi}:H22", "H", "",
         -2.193, 0.813, 0.066, start_idx + 32],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.969),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H2''", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H8", f"A{res:04d}-{resi}:C8", 0.930),
        (f"A{res:04d}-{resi}:H21", f"A{res:04d}-{resi}:N2", 0.860),
        (f"A{res:04d}-{resi}:H22", f"A{res:04d}-{resi}:N2", 0.860),
        (f"A{res:04d}-{resi}:H1", f"A{res:04d}-{resi}:N1", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.523, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.452, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.632, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.478, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.969, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.500, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.403, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.548, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.448, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.514, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.524, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.461, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.362, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.331, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.339, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.344, "base": True}),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.240, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.424, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.378, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.377, "base": True}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.315, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.368, "base": True}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.467, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:H8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:H21",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:H22",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.339, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:H1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.376, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.393, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N2", {"weight": 0}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:O6", {"weight": 0}),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N7", {"weight": 0}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C8", {"weight": 0}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N9", {"weight": 0}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N9": 1,
        f"A{res:04d}-{resi}:C8": 1,
        f"A{res:04d}-{resi}:N7": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
        f"A{res:04d}-{resi}:O6": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:N2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7", 5),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", 5),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_thymine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "DT".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         -1.703, -7.661, -0.122, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         -2.937, -8.598, -0.058, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         -0.549, -8.314, -0.793, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         -2.289, -6.290, -0.712, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -3.525, -5.891, -0.062, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -3.759, -4.444, -0.326, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -2.758, -3.592, 0.218, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -3.886, -4.083, -1.813, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -4.963, -3.186, -2.008, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -2.545, -3.354, -2.063, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -2.522, -2.537, -0.787, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         -1.236, -1.890, -0.604, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.214, -0.570, -0.185, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "O2", f"A{res:04d}-{resi}:O2", "O", "",
         -2.283, 0.015, 0.000, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         0.000, 0.029, 0.000, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         1.173, -0.628, -0.209, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "O4", f"A{res:04d}-{resi}:O4", "O", "",
         2.258, -0.014, 0.000, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.138, -1.989, -0.634, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C7", f"A{res:04d}-{resi}:C7", "C", "",
         2.388, -2.783, -0.879, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         -0.063, -2.561, -0.812, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -3.471, -6.054, 0.893, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -4.267, -6.418, -0.398, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -4.607, -4.294, 0.120, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -4.050, -4.841, -2.395, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -1.791, -3.959, -2.141, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H2''", f"A{res:04d}-{resi}:H2''", "H", "",
         -2.553, -2.806, -2.865, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -3.163, -1.810, -0.756, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H3", f"A{res:04d}-{resi}:H3", "H", "",
         0.023, 0.849, 0.258, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H71", f"A{res:04d}-{resi}:H71", "H", "",
         2.218, -3.720, -0.693, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H72", f"A{res:04d}-{resi}:H72", "H", "",
         2.659, -2.682, -1.804, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H73", f"A{res:04d}-{resi}:H73", "H", "",
         3.095, -2.462, -0.298, start_idx + 30],
        ["ATOM", start_idx + 31, "A", res, "", resi, "H6", f"A{res:04d}-{resi}:H6", "H", "",
         -0.098, -3.448, -1.088, start_idx + 31],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H2''", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H6", f"A{res:04d}-{resi}:C6", 0.930),
        (f"A{res:04d}-{resi}:H71", f"A{res:04d}-{resi}:C7", 0.970),
        (f"A{res:04d}-{resi}:H72", f"A{res:04d}-{resi}:C7", 0.970),
        (f"A{res:04d}-{resi}:H73", f"A{res:04d}-{resi}:C7", 0.970),
        (f"A{res:04d}-{resi}:H3", f"A{res:04d}-{resi}:N3", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.551, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.486, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.604, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.453, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.489, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.422, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.535, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.415, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.547, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.515, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.476, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.451, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.368, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.342, "base": True}),
        (f"A{res:04d}-{resi}:C7", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.501, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.385, "base": True}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.232, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.366, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.361, "base": True}),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.264, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:H6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:C7", f"A{res:04d}-{resi}:H71",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C7", f"A{res:04d}-{resi}:H72",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C7", f"A{res:04d}-{resi}:H73",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:H3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.425, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C7", {"weight": 0}),
        (f"A{res:04d}-{resi}:C7", f"A{res:04d}-{resi}:C5", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:O2", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:O4", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:O2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
        f"A{res:04d}-{resi}:O4": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C7": 1,
        f"A{res:04d}-{resi}:C6": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", 5),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )
