from typing import Optional, List, Tuple

from TRAMbio.util.constants.interaction import InteractionType
from tests.util.protein_graph_utils import *

def graph_adenine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "A".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         2.981, -7.828, -1.343, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         3.042, -9.025, -2.223, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         4.002, -6.764, -1.516, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         1.520, -7.189, -1.392, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         0.376, -7.948, -1.022, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -0.846, -7.074, -0.907, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -0.714, -6.195, 0.242, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -1.092, -6.122, -2.067, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -1.701, -6.747, -3.183, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -1.941, -5.037, -1.426, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "O2'", f"A{res:04d}-{resi}:O2'", "O", "",
         -3.278, -5.484, -1.247, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -1.281, -4.931, -0.052, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "N9", f"A{res:04d}-{resi}:N9", "N", "",
         -0.201, -3.922, -0.037, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "C8", f"A{res:04d}-{resi}:C8", "C", "",
         1.152, -4.164, -0.044, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "N7", f"A{res:04d}-{resi}:N7", "N", "",
         1.894, -3.086, -0.032, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         0.966, -2.055, -0.019, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         1.121, -0.660, -0.005, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "N6", f"A{res:04d}-{resi}:N6", "N", "",
         2.317, -0.061, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         0.000, 0.102, 0.000, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.193, -0.512, -0.006, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         -1.463, -1.817, -0.020, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         -0.329, -2.546, -0.026, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         0.541, -8.393, -0.176, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         0.219, -8.642, -1.681, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -1.573, -7.715, -0.859, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -0.276, -5.774, -2.459, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -1.984, -4.217, -1.941, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "HO2'", f"A{res:04d}-{resi}:HO2'", "H", "",
         -3.408, -6.172, -1.711, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -1.948, -4.664, 0.600, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H8", f"A{res:04d}-{resi}:H8", "H", "",
         1.510, -5.022, -0.057, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H61", f"A{res:04d}-{resi}:H61", "H", "",
         2.368, 0.797, 0.008, start_idx + 30],
        ["ATOM", start_idx + 31, "A", res, "", resi, "H62", f"A{res:04d}-{resi}:H62", "H", "",
         3.036, -0.534, -0.005, start_idx + 31],
        ["ATOM", start_idx + 32, "A", res, "", resi, "H2", f"A{res:04d}-{resi}:H2", "H", "",
         -1.933, 0.051, 0.000, start_idx + 32],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.969),
        (f"A{res:04d}-{resi}:HO2'", f"A{res:04d}-{resi}:O2'", 0.840),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H8", f"A{res:04d}-{resi}:C8", 0.930),
        (f"A{res:04d}-{resi}:H61", f"A{res:04d}-{resi}:N6", 0.860),
        (f"A{res:04d}-{resi}:H62", f"A{res:04d}-{resi}:N6", 0.860),
        (f"A{res:04d}-{resi}:H2", f"A{res:04d}-{resi}:C2", 0.930),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.486, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.485, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.595, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.421, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.507, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.453, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.521, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.416, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.520, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.969, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.421, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:HO2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.840, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.528, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.416, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.341, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.332, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.348, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.338, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.403, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.385, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.382, "base": True}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.309, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.374, "base": True}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.478, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:H8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:H61",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:H62",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:H2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.356, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.387, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:O2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N6", {"weight": 0}),
        (f"A{res:04d}-{resi}:N6", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N7", {"weight": 0}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C8", {"weight": 0}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N9", {"weight": 0}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:O2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N9": 1,
        f"A{res:04d}-{resi}:C8": 1,
        f"A{res:04d}-{resi}:N7": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
        f"A{res:04d}-{resi}:N6": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7", 5),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", 6),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", 1),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_cytosine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "C".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         -0.172, -7.328, -1.809, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         -0.900, -8.304, -2.660, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         1.236, -6.983, -2.150, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         -1.038, -5.996, -1.649, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -2.450, -6.059, -1.540, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -3.062, -4.708, -1.235, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -2.377, -4.069, -0.127, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -2.994, -3.666, -2.326, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -3.910, -3.897, -3.378, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -3.248, -2.372, -1.546, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "O2'", f"A{res:04d}-{resi}:O2'", "O", "",
         -4.628, -2.196, -1.266, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -2.534, -2.666, -0.230, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         -1.212, -2.025, -0.168, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.180, -0.628, -0.052, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "O2", f"A{res:04d}-{resi}:O2", "O", "",
         -2.239, 0.011, 0.000, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         0.000, 0.021, 0.000, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         1.128, -0.683, -0.068, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "N4", f"A{res:04d}-{resi}:N4", "N", "",
         2.275, -0.011, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.130, -2.105, -0.202, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         -0.052, -2.738, -0.253, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -2.691, -6.687, -0.842, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -2.821, -6.401, -2.369, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -3.988, -4.949, -1.073, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -2.150, -3.656, -2.804, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -2.955, -1.579, -2.023, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "HO2'", f"A{res:04d}-{resi}:HO2'", "H", "",
         -4.879, -2.781, -0.718, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -3.064, -2.312, 0.501, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H41", f"A{res:04d}-{resi}:H41", "H", "",
         3.024, -0.432, -0.040, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H42", f"A{res:04d}-{resi}:H42", "H", "",
         2.268, 0.845, 0.084, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H5", f"A{res:04d}-{resi}:H5", "H", "",
         1.928, -2.579, -0.252, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H6", f"A{res:04d}-{resi}:H6", "H", "",
         -0.081, -3.663, -0.347, start_idx + 30],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:HO2'", f"A{res:04d}-{resi}:O2'", 0.840),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H6", f"A{res:04d}-{resi}:C6", 0.931),
        (f"A{res:04d}-{resi}:H5", f"A{res:04d}-{resi}:C5", 0.930),
        (f"A{res:04d}-{resi}:H41", f"A{res:04d}-{resi}:N4", 0.860),
        (f"A{res:04d}-{resi}:H42", f"A{res:04d}-{resi}:N4", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.485, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.489, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.597, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.418, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.514, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.451, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.511, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.414, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.532, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.418, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:HO2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.840, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.526, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.415, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.471, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.364, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.342, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.402, "base": True}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.238, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.348, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.331, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.331, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:H6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.931, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:H5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:H41",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:H42",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.429, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:O2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:O2", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N4", {"weight": 0}),
        (f"A{res:04d}-{resi}:N4", f"A{res:04d}-{resi}:C4", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:O2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:O2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
        f"A{res:04d}-{resi}:N4": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", 5),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", 1),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_guanine(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "G".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         3.672, -7.975, -0.215, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         3.597, -9.382, -0.681, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         4.668, -7.067, -0.845, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         2.226, -7.313, -0.263, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         1.060, -8.108, -0.123, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -0.187, -7.308, -0.392, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -0.321, -6.260, 0.607, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -0.219, -6.548, -1.705, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -0.531, -7.355, -2.824, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -1.243, -5.466, -1.418, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "O2'", f"A{res:04d}-{resi}:O2'", "O", "",
         -2.555, -6.008, -1.394, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -0.853, -5.094, 0.005, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "N9", f"A{res:04d}-{resi}:N9", "N", "",
         0.183, -4.042, 0.019, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "C8", f"A{res:04d}-{resi}:C8", "C", "",
         1.552, -4.190, 0.006, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "N7", f"A{res:04d}-{resi}:N7", "N", "",
         2.195, -3.053, 0.003, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.192, -2.094, 0.004, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         1.267, -0.677, 0.002, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "O6", f"A{res:04d}-{resi}:O6", "O", "",
         2.269, 0.051, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         0.000, -0.103, 0.000, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.188, -0.793, 0.000, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "N2", f"A{res:04d}-{resi}:N2", "N", "",
         -2.306, -0.051, 0.000, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         -1.270, -2.111, 0.003, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         -0.051, -2.690, 0.003, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         1.023, -8.476, 0.774, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         1.102, -8.859, -0.736, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -0.886, -7.981, -0.391, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         0.646, -6.194, -1.966, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -1.250, -4.744, -2.066, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "HO2'", f"A{res:04d}-{resi}:HO2'", "H", "",
         -3.049, -5.569, -1.911, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -1.630, -4.758, 0.479, start_idx + 29],
        ["ATOM", start_idx + 30, "A", res, "", resi, "H8", f"A{res:04d}-{resi}:H8", "H", "",
         1.977, -5.017, -0.001, start_idx + 30],
        ["ATOM", start_idx + 31, "A", res, "", resi, "H1", f"A{res:04d}-{resi}:H1", "H", "",
         -0.043, 0.756, -0.002, start_idx + 31],
        ["ATOM", start_idx + 32, "A", res, "", resi, "H21", f"A{res:04d}-{resi}:H21", "H", "",
         -3.076, -0.434, 0.000, start_idx + 32],
        ["ATOM", start_idx + 33, "A", res, "", resi, "H22", f"A{res:04d}-{resi}:H22", "H", "",
         -2.252, 0.807, 0.000, start_idx + 33],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:HO2'", f"A{res:04d}-{resi}:O2'", 0.840),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.970),
        (f"A{res:04d}-{resi}:H8", f"A{res:04d}-{resi}:C8", 0.930),
        (f"A{res:04d}-{resi}:H21", f"A{res:04d}-{resi}:N2", 0.860),
        (f"A{res:04d}-{resi}:H22", f"A{res:04d}-{resi}:N2", 0.860),
        (f"A{res:04d}-{resi}:H1", f"A{res:04d}-{resi}:N1", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.484, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.488, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.591, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.418, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.506, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.454, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.518, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.415, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.517, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.420, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:HO2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.840, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.522, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.416, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.374, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.321, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.341, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.349, "base": True}),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.238, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.419, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.379, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.372, "base": True}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.306, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.376, "base": True}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.477, "base": True}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:H8",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:H21",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:H22",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.341, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:H1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.391, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.388, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:O2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N2", {"weight": 0}),
        (f"A{res:04d}-{resi}:N2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:O6", {"weight": 0}),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N7", {"weight": 0}),
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", {"weight": 5}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C8", {"weight": 0}),
        (f"A{res:04d}-{resi}:C8", f"A{res:04d}-{resi}:N9", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N9", {"weight": 0}),
        (f"A{res:04d}-{resi}:N9", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:O2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N9": 1,
        f"A{res:04d}-{resi}:C8": 1,
        f"A{res:04d}-{resi}:N7": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
        f"A{res:04d}-{resi}:O6": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:N2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:N7", f"A{res:04d}-{resi}:C8", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N9", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C4", 1),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:N7", 5),
        (f"A{res:04d}-{resi}:O6", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", 5),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", 1),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )

def graph_uracil(
        start_idx: int = 1,
        res: int = 1,
        x_offset: float = 0.0,
        y_offset: float = 0.0,
        z_offset: float = 0.0,
        rotations: Optional[List[Tuple[float, AXIS_OPTIONS]]] = None,
        exclude: Optional[List[str]] = None
):
    resi = "U".rjust(3, " ")
    coords = modify_coords(apply_rotations([
        ["ATOM", start_idx, "A", res, "", resi, "P", f"A{res:04d}-{resi}:P", "P", "",
         0.062, -7.257, -2.321, start_idx],
        ["ATOM", start_idx + 1, "A", res, "", resi, "OP1", f"A{res:04d}-{resi}:OP1", "O", "",
         -0.756, -8.167, -3.163, start_idx + 1],
        ["ATOM", start_idx + 2, "A", res, "", resi, "OP2", f"A{res:04d}-{resi}:OP2", "O", "",
         1.365, -6.776, -2.852, start_idx + 2],
        ["ATOM", start_idx + 3, "A", res, "", resi, "O5'", f"A{res:04d}-{resi}:O5'", "O", "",
         -0.822, -6.015, -1.834, start_idx + 3],
        ["ATOM", start_idx + 4, "A", res, "", resi, "C5'", f"A{res:04d}-{resi}:C5'", "C", "",
         -2.017, -6.214, -1.090, start_idx + 4],
        ["ATOM", start_idx + 5, "A", res, "", resi, "C4'", f"A{res:04d}-{resi}:C4'", "C", "",
         -2.804, -4.935, -0.935, start_idx + 5],
        ["ATOM", start_idx + 6, "A", res, "", resi, "O4'", f"A{res:04d}-{resi}:O4'", "O", "",
         -2.260, -4.140, 0.149, start_idx + 6],
        ["ATOM", start_idx + 7, "A", res, "", resi, "C3'", f"A{res:04d}-{resi}:C3'", "C", "",
         -2.787, -3.980, -2.117, start_idx + 7],
        ["ATOM", start_idx + 8, "A", res, "", resi, "O3'", f"A{res:04d}-{resi}:O3'", "O", "",
         -3.653, -4.368, -3.168, start_idx + 8],
        ["ATOM", start_idx + 9, "A", res, "", resi, "C2'", f"A{res:04d}-{resi}:C2'", "C", "",
         -3.168, -2.652, -1.473, start_idx + 9],
        ["ATOM", start_idx + 10, "A", res, "", resi, "O2'", f"A{res:04d}-{resi}:O2'", "O", "",
         -4.569, -2.572, -1.267, start_idx + 10],
        ["ATOM", start_idx + 11, "A", res, "", resi, "C1'", f"A{res:04d}-{resi}:C1'", "C", "",
         -2.484, -2.765, -0.111, start_idx + 11],
        ["ATOM", start_idx + 12, "A", res, "", resi, "N1", f"A{res:04d}-{resi}:N1", "N", "",
         -1.188, -2.043, -0.082, start_idx + 12],
        ["ATOM", start_idx + 13, "A", res, "", resi, "C2", f"A{res:04d}-{resi}:C2", "C", "",
         -1.232, -0.648, -0.026, start_idx + 13],
        ["ATOM", start_idx + 14, "A", res, "", resi, "O2", f"A{res:04d}-{resi}:O2", "O", "",
         -2.279, -0.012, 0.000, start_idx + 14],
        ["ATOM", start_idx + 15, "A", res, "", resi, "N3", f"A{res:04d}-{resi}:N3", "N", "",
         0.000, -0.023, 0.000, start_idx + 15],
        ["ATOM", start_idx + 16, "A", res, "", resi, "C4", f"A{res:04d}-{resi}:C4", "C", "",
         1.230, -0.662, -0.027, start_idx + 16],
        ["ATOM", start_idx + 17, "A", res, "", resi, "O4", f"A{res:04d}-{resi}:O4", "O", "",
         2.259, 0.012, 0.000, start_idx + 17],
        ["ATOM", start_idx + 18, "A", res, "", resi, "C5", f"A{res:04d}-{resi}:C5", "C", "",
         1.189, -2.095, -0.086, start_idx + 18],
        ["ATOM", start_idx + 19, "A", res, "", resi, "C6", f"A{res:04d}-{resi}:C6", "C", "",
         0.011, -2.725, -0.113, start_idx + 19],
        ["ATOM", start_idx + 20, "A", res, "", resi, "H5'", f"A{res:04d}-{resi}:H5'", "H", "",
         -1.797, -6.566, -0.214, start_idx + 20],
        ["ATOM", start_idx + 21, "A", res, "", resi, "H5''", f"A{res:04d}-{resi}:H5''", "H", "",
         -2.566, -6.879, -1.534, start_idx + 21],
        ["ATOM", start_idx + 22, "A", res, "", resi, "H4'", f"A{res:04d}-{resi}:H4'", "H", "",
         -3.707, -5.262, -0.802, start_idx + 22],
        ["ATOM", start_idx + 23, "A", res, "", resi, "H3'", f"A{res:04d}-{resi}:H3'", "H", "",
         -1.929, -3.951, -2.568, start_idx + 23],
        ["ATOM", start_idx + 24, "A", res, "", resi, "H2'", f"A{res:04d}-{resi}:H2'", "H", "",
         -2.917, -1.880, -2.005, start_idx + 24],
        ["ATOM", start_idx + 25, "A", res, "", resi, "HO2'", f"A{res:04d}-{resi}:HO2'", "H", "",
         -4.791, -3.095, -0.648, start_idx + 25],
        ["ATOM", start_idx + 26, "A", res, "", resi, "H1'", f"A{res:04d}-{resi}:H1'", "H", "",
         -3.056, -2.363, 0.563, start_idx + 26],
        ["ATOM", start_idx + 27, "A", res, "", resi, "H3", f"A{res:04d}-{resi}:H3", "H", "",
         0.004, 0.836, 0.035, start_idx + 27],
        ["ATOM", start_idx + 28, "A", res, "", resi, "H5", f"A{res:04d}-{resi}:H5", "H", "",
         1.980, -2.584, -0.105, start_idx + 28],
        ["ATOM", start_idx + 29, "A", res, "", resi, "H6", f"A{res:04d}-{resi}:H6", "H", "",
         -0.002, -3.654, -0.155, start_idx + 29],
    ], rotations), x_offset, y_offset, z_offset)
    hydrogen_mapping = [
        (f"A{res:04d}-{resi}:H5'", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H5''", f"A{res:04d}-{resi}:C5'", 0.970),
        (f"A{res:04d}-{resi}:H4'", f"A{res:04d}-{resi}:C4'", 0.970),
        (f"A{res:04d}-{resi}:H3'", f"A{res:04d}-{resi}:C3'", 0.970),
        (f"A{res:04d}-{resi}:H2'", f"A{res:04d}-{resi}:C2'", 0.970),
        (f"A{res:04d}-{resi}:HO2'", f"A{res:04d}-{resi}:O2'", 0.840),
        (f"A{res:04d}-{resi}:H1'", f"A{res:04d}-{resi}:C1'", 0.971),
        (f"A{res:04d}-{resi}:H6", f"A{res:04d}-{resi}:C6", 0.930),
        (f"A{res:04d}-{resi}:H5", f"A{res:04d}-{resi}:C5", 0.930),
        (f"A{res:04d}-{resi}:H3", f"A{res:04d}-{resi}:N3", 0.860),
    ]
    covalent_edges = [
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.485, "base": True}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.487, "base": True}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.601, "base": True}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.422, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:H5''",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.510, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:H4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.449, "base": True}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.520, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.416, "base": True}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:H3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.525, "base": True}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:H2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.970, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.417, "base": True}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:HO2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.840, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.528, "base": True}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.418, "base": True}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:H1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.971, "base": True}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.484, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.379, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.336, "base": True}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.397, "base": True}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.226, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.381, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.387, "base": True}),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.230, "base": True}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:H6",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:H5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.930, "base": True}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:H3",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 0.860, "base": True}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5",
         {"kind": {InteractionType.COVALENT.value}, "bond_length": 1.434, "base": True}),
    ]
    pebble_edges = [
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP1", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:OP2", {"weight": 0}),
        (f"A{res:04d}-{resi}:OP2", f"A{res:04d}-{resi}:P", {"weight": 5}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:P", {"weight": 0}),
        (f"A{res:04d}-{resi}:P", f"A{res:04d}-{resi}:O5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:O5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O5'", f"A{res:04d}-{resi}:C5'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C5'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:O4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C4'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C4'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:O3'", f"A{res:04d}-{resi}:C3'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:O3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C3'", f"A{res:04d}-{resi}:C2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C3'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:O2'", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2'", f"A{res:04d}-{resi}:C1'", {"weight": 0}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:C2'", {"weight": 5}),
        (f"A{res:04d}-{resi}:C1'", f"A{res:04d}-{resi}:N1", {"weight": 0}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C1'", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C6", {"weight": 0}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C6", f"A{res:04d}-{resi}:C5", {"weight": 0}),
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", {"weight": 5}),
        (f"A{res:04d}-{resi}:N1", f"A{res:04d}-{resi}:C2", {"weight": 0}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N1", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:O2", {"weight": 0}),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:C2", f"A{res:04d}-{resi}:N3", {"weight": 0}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C2", {"weight": 5}),
        (f"A{res:04d}-{resi}:N3", f"A{res:04d}-{resi}:C4", {"weight": 0}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:N3", {"weight": 5}),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:O4", {"weight": 0}),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4", {"weight": 5}),
    ]
    pebble_map = {
        f"A{res:04d}-{resi}:P": 1,
        f"A{res:04d}-{resi}:OP1": 1,
        f"A{res:04d}-{resi}:OP2": 1,
        f"A{res:04d}-{resi}:O5'": 1,
        f"A{res:04d}-{resi}:C5'": 1,
        f"A{res:04d}-{resi}:C4'": 1,
        f"A{res:04d}-{resi}:O4'": 1,
        f"A{res:04d}-{resi}:C3'": 1,
        f"A{res:04d}-{resi}:O3'": 6,
        f"A{res:04d}-{resi}:C2'": 1,
        f"A{res:04d}-{resi}:O2'": 1,
        f"A{res:04d}-{resi}:C1'": 1,
        f"A{res:04d}-{resi}:N1": 1,
        f"A{res:04d}-{resi}:C2": 1,
        f"A{res:04d}-{resi}:O2": 1,
        f"A{res:04d}-{resi}:N3": 1,
        f"A{res:04d}-{resi}:C4": 1,
        f"A{res:04d}-{resi}:O4": 1,
        f"A{res:04d}-{resi}:C5": 1,
        f"A{res:04d}-{resi}:C6": 1,
    }
    pebble_bars = [
        (f"A{res:04d}-{resi}:C5", f"A{res:04d}-{resi}:C6", 1),
        (f"A{res:04d}-{resi}:O2", f"A{res:04d}-{resi}:C2", 1),
        (f"A{res:04d}-{resi}:C4", f"A{res:04d}-{resi}:C5", 5),
        (f"A{res:04d}-{resi}:O4", f"A{res:04d}-{resi}:C4", 1),
        # Backbone
        (f"A{res:04d}-{resi}:OP1", f"A{res:04d}-{resi}:OP2", 2),
        (f"A{res:04d}-{resi}:O4'", f"A{res:04d}-{resi}:C1'", 5),
        (f"A{res:04d}-{resi}:O2'", f"A{res:04d}-{resi}:C2'", 1),
    ]

    return format_coords(
        coords=coords, hydrogen_mapping=hydrogen_mapping, covalent_edges=covalent_edges,
        pebble_edges=pebble_edges, pebble_map=pebble_map, pebble_bars=pebble_bars,
        exclude=exclude
    )
