name: PyPI

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}-${{ github.workflow }}"
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - "main"
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'release/') }}  # ignore automatic pull_requests from release branches

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build
      - name: Check README rendering for PyPI
        run: |
          python3 -m pip install twine
          twine check dist/*
      - name: Store the distribution packages
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: python-package-distributions
          path: |
            dist/
            CHANGELOG.md

  publish-to-pypi:
    name: >-
      Publish Python distribution to PyPI
    if: ${{ success() && github.repository == 'gate-tec/TRAMbio' && startsWith(github.ref, 'refs/tags/v') }}  # only publish to PyPI on tag pushes
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/TRAMbio
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: python-package-distributions
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4

  github-release:
    name: >-
      Sign the Python distribution with Sigstore
      and upload them to GitHub Release
    needs:
      - publish-to-pypi
    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: python-package-distributions
      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@f514d46b907ebcd5bedc05145c03b69c1edd8b46  # v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            dist/**
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

  publish-to-testpypi:
    name: Publish Python distribution to TestPyPI
    if: ${{ github.repository == 'gate-tec/TRAMbio' && !startsWith(github.ref, 'refs/tags/v') }}
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/TRAMbio

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093  # v4.3.0
        with:
          name: python-package-distributions
      - name: Publish distribution to TestPyPI
        continue-on-error: true
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # 1.12.4
        with:
          repository-url: https://test.pypi.org/legacy/

  check-testpypi:
    name: Check python distribution from TestPyPI
    needs:
      - publish-to-testpypi
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "3.10"
      - name: Download from testpypi
        continue-on-error: true
        run: >-
          python3 -m pip install
          --index-url https://test.pypi.org/simple/
          --extra-index-url https://pypi.org/simple/
          TRAMbio[all]
